global left_fit
global right_fit
global right_curverad
global left_curverad
global prev_left
global prev_right
global prev_prev_right
global prev_prev_left
global pts_left
global pts_right
global x